### PR TITLE
Modified column names, fixed sql queries

### PR DESCRIPTION
**Pull request by rhiannonlynne**
This version should run all the way through modifySchema. 
I'm creating a test output sqlite file now and will send you that to evaluate whether the dithering did as you wanted.

### CODE REVIEW

**Comment by humnaawan** [comment]
@rhiannonlynne @egawiser so I checked the sqlite database you generated with this extension. You can see the notebook [here](https://github.com/humnaawan/MAF-Related-Notebooks/blob/master/Afterburner%20Extension%20--%20Check%20Sqlite%20Database.ipynb). 

Rotational dithers are not working -- the dithering is fine up (i.e. want no dithering) until the first filter change but then the dithers are being implemented with every observation (see Output[18] in the notebook). I looked at your updates to the code and I think it has to do with `prevFilter` not being updated at any point in the loop that started on your line 387 in `prep_opsim.py`. I think we need `prevFilter= filterBand` in the loop `if (filterBand != prevFilter): `

Hex dithers appear to be working in terms of their implementation timescale. However, the xOffset and yOffset don't match when I compare the afterburner output with maf output (see Output[15]). Not sure why that is.

As for random dithers, I can see that the implementation timescale is fine since we are getting different offsets every visit (see Output[8]). However, I cannot do a direct comparison since the random seed is never set in the afterburner so the random numbers wont be the same. 

Since we'll need to run the afterburner with the rotational dither fix, could we add a random seed to both random translational dithers (say in the `offsetRandom` function) and the rotational ones (will need to find all the random numbers outside of the loop on line 387..? ) so that I can compare things more directly?

**Comment by rhiannonlynne** [comment]
Sorry about the silly mistake with the rotational dithers. Good idea about setting a random seed, although I will note that I still don't think you will get exactly the same thing with the MAF results in your notebook as with the afterburner. This is because the afterburner is running on all observations (not just WFD) and the results of sql queries that do not have an explicit 'order by ' clause can be unpredictable. If you need to do a pointing-by-pointing comparison, you could select all observations from MAF (not just WFD), and then sort by expMJD, and I could add an 'order by expMJD' to the afterburner sql query. 

As for the hexDither offsets not quite matching .. the opsim ones don't take into account the "inHex" requirement, which shrinks the grid by 5% (0.95 * each dither offset), so I would guess that's where that difference comes from. I'll add that option to the opsim afterburner, and turn it on.

**Comment by rhiannonlynne** [comment]
[lucy_1000_sqlite.db.gz](https://github.com/humnaawan/sims_operations/files/717858/lucy_1000_sqlite.db.gz)
 
Here is an extremely short (3 day) test of the new dithers. Is this enough to check the evaluation of the dithering?

**Comment by rhiannonlynne** [comment]
New version of astro_lsst_01_1000 uploaded at 
http://www.astro.washington.edu/users/lynnej/astro_lsst_01_1000_sqlite.db

**Comment by humnaawan** [comment]
@rhiannonlynne thanks! I re-ran the [notebook](https://github.com/humnaawan/MAF-Related-Notebooks/blob/master/Afterburner%20Extension%20--%20Check%20Sqlite%20Database.ipynb) with your lucy output and the rotational dithers are now working (see Output[18]). Also, the inHex restriction on hexDithers has corrected the small differences I was seeing before so the afterburner  now adds the same dithers as the maf hex perNight stacker (Output[15]).

As for the randomFieldPerVisit columns, I added the seed (=42) in the notebook but as before, I am not finding RA, Dec offsets (more precisely, xOffset and yOffset=decOffset) to be the same. I am not sure why WFD or expMJD should matter -- the notebook takes your output, uses its 'original' columns (fieldRA, fieldDec, etc.) and uses them with the stackers, so things should be working. I am not seeing any preferential bias in the afterburner's random dithers though.

I am downloading the new astro_lsst output, but things look good so far. Let me know what you think.

**Comment by rhiannonlynne** [comment]
Sounds good! The random dithers are likely different because the maf
stacker gets different information , in a different order, than the
afterburner random dither did. For example, if there was 2 wfd observations
and then 3 scp observations, then 4 more wfd visits, then the afterburner
would assign the random offsets sequentially to these visits (e.g., random
offset #4 would be one of the scp visits the). But the maf stacker, because
you only pulled out wfd visits in the first place, wouldn't know about the
scp visit and so random offset #4 would go to the 4th wfd visit. Also, maf
may not select the visits from the database in expmjd order (it probably
will, but is not guaranteed to, which is why you see some metrics sorting
by expmjd). But it sounds like it's ready to go, to me :)

**Comment by humnaawan** [comment]
Oh ok -- sorry, I forgot about my sqlconstraint on your output. Thanks for explaining!

And I ran the notebook with the astro output. Things look good.

**Pull request merged**
